# Generated by Django 3.0.5 on 2020-05-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20190919_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='active',
            new_name='is_active',
        ),
    ]
