# Generated by Django 3.0.5 on 2020-05-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_auto_20200520_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='is_active',
            new_name='active',
        ),
    ]
